version: '3.4'

services:
    nginx_test:
        build:
            context: .
            dockerfile: Dockerfile
            network: docker_testnet
        image: nginx_test
        restart: always
        ports:
            - 9980:80
        networks:
            - testnet
  
networks:
    testnet:
        driver: bridge